# Generated by Django 5.2.7 on 2025-10-07 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('input_reagent', models.CharField(max_length=100)),
                ('output_product', models.CharField(max_length=100)),
                ('input_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.URLField(blank=True, null=True)),
                ('reaction_equation', models.TextField()),
                ('parameter_name', models.CharField(max_length=100)),
                ('parameter_unit', models.CharField(max_length=20)),
                ('parameter_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parameter_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parameter_default', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
