# Generated by Django 5.2.7 on 2025-10-07 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irc_lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('FORMED', 'Formed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('target_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('safety_factor', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('calculation_date', models.DateField()),
                ('total_input_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_calculations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_calculations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=1)),
                ('is_main', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('calculation_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irc_lab.calculation')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irc_lab.process')),
            ],
            options={
                'unique_together': {('calculation', 'process')},
            },
        ),
    ]
