# Generated by Django 5.2.7 on 2025-10-19 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irc_lab', '0002_calculation_processincalculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Process',
            new_name='ChemicalProcess',
        ),
        migrations.RenameModel(
            old_name='Calculation',
            new_name='ReagentCalculation',
        ),
        migrations.CreateModel(
            name='ChemicalProcessInReagentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('calculation_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irc_lab.reagentcalculation')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irc_lab.chemicalprocess')),
            ],
            options={
                'unique_together': {('calculation', 'process')},
            },
        ),
        migrations.DeleteModel(
            name='ProcessInCalculation',
        ),
    ]
