# Generated by Django 5.2.7 on 2025-10-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irc_lab', '0003_rename_process_chemicalprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalprocessinreagentcalculation',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chemicalprocessinreagentcalculation',
            name='calculation_result',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
