# Generated by Django 5.2.7 on 2025-11-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irc_lab', '0005_reagentcalculation_results_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalprocessinreagentcalculation',
            name='comment',
        ),
    ]
