# Generated by Django 5.2.7 on 2025-11-18 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irc_lab', '0006_remove_chemicalprocessinreagentcalculation_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentcalculation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reagentcalculation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_calculations', to=settings.AUTH_USER_MODEL),
        ),
    ]
